export const BUILT_IN_PROVIDER_DISPLAY_NAMES: Record<string, string> = {
	anthropic: "Anthropic",
	"alibaba-coding-plan": "Alibaba Qwen Coding Plan",
	"alibaba-coding-plan-cn": "Alibaba Qwen Coding Plan (China)",
	"azure-openai-responses": "Azure OpenAI Responses",
	cerebras: "Cerebras",
	cursor: "Cursor",
	"cloudflare-ai-gateway": "Cloudflare AI Gateway",
	"cloudflare-workers-ai": "Cloudflare Workers AI",
	deepseek: "DeepSeek",
	fireworks: "Fireworks",
	google: "Google Gemini",
	grok: "Grok (SuperGrok)",
	groq: "Groq",
	huggingface: "Hugging Face",
	"kimi-coding": "Kimi For Coding",
	mistral: "Mistral",
	nous: "Nous Portal",
	gmi: "GMI Cloud",
	minimax: "MiniMax",
	"minimax-cn": "MiniMax (China)",
	moonshotai: "Moonshot AI",
	"moonshotai-cn": "Moonshot AI (China)",
	opencode: "OpenCode Zen",
	"opencode-go": "OpenCode Go",
	openai: "OpenAI",
	openrouter: "OpenRouter",
	"vercel-ai-gateway": "Vercel AI Gateway",
	xai: "xAI",
	zai: "Z.ai (GLM Coding Plan)",
	"zhipuai-coding-plan": "Zhipu GLM Coding Plan (China)",
	"tencent-coding-plan": "Tencent Coding Plan",
	nvidia: "NVIDIA NIM",
	siliconflow: "SiliconFlow",
	togetherai: "Together AI",
	xiaomi: "Xiaomi MiMo",
	"xiaomi-token-plan-cn": "Xiaomi MiMo Token Plan (China)",
	"xiaomi-token-plan-ams": "Xiaomi MiMo Token Plan (Amsterdam)",
	"xiaomi-token-plan-sgp": "Xiaomi MiMo Token Plan (Singapore)",
};
